---
abstract: 'Generate voiD descriptions based on data in an RDF model.'
author:
  - 'Kjetil Kjernsmo <kjetilk@cpan.org>'
  - 'Konstantin Baierer <kba@cpan.org>'
  - 'Toby Inkster'
build_requires:
  ExtUtils::MakeMaker: 6.36
  File::Temp: 0
  FindBin: 0
  Test::More: 0.88
  Test::RDF: 1.10
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: RDF::Generator::Void
name: RDF-Generator-Void
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  App::perlrdf: 0
requires:
  Data::UUID: 0
  Moose: 0
  RDF::Trine: 0
  URI: 0
  aliased: 0
  perl: 5.005
resources:
  bugtracker: https://github.com/kjetilk/RDF-Generator-Void/issues
  license: http://dev.perl.org/licenses/
version: 0.11_1
