---
abstract: 'Generate VoID descriptions based on data in an RDF model'
author:
  - 'Kjetil Kjernsmo C<< <kjetilk@cpan.org> >>'
  - 'Kjetil Kjernsmo <kjetilk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  FindBin: 0
  Test::More: 0.88
  Test::RDF: 1.1
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-Generator-Void
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Data::UUID: 0
  Moose: 0
  RDF::Trine: 0
  URI: 0
  aliased: 0
  perl: 5.6.0
resources:
  bugtracker: https://github.com/kjetilk/RDF-Generator-Void/issues
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kjetilk/RDF-Generator-Void.git
version: 0.07_1
